# Generated by Django 4.0 on 2021-12-21 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_test', models.CharField(max_length=150, verbose_name='Название теста')),
                ('questions_count', models.IntegerField(blank=True, verbose_name='Сколько вопросов в тесте?')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300, verbose_name='Название')),
                ('Content', models.TextField(blank=True, verbose_name='Описание')),
                ('QuesType', models.IntegerField(blank=True, default=0, verbose_name='Тип вопроса')),
                ('Audio', models.FileField(blank=True, upload_to='', verbose_name='Аудиозапись')),
                ('ProfileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quests.profiletest', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=300, verbose_name='ФИО')),
                ('Rating', models.FloatField(verbose_name='Проценты')),
                ('ProfileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quests.profiletest', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=1000)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.CharField(blank=True, max_length=200, verbose_name='Ответ')),
                ('IsRight', models.BooleanField(blank=True, verbose_name='Правильный?')),
                ('DescriptionForAnswer', models.TextField(blank=True, max_length=100, verbose_name='Описание к ответу')),
                ('QuestionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quests.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
            },
        ),
        migrations.CreateModel(
            name='Responds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.TextField(verbose_name='Ответ')),
                ('VideoAnswer', models.FileField(blank=True, upload_to='videos/answers/', verbose_name='Видео')),
                ('QuestionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quests.question', verbose_name='Вопрос')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
                'unique_together': {('UserId', 'QuestionID')},
            },
        ),
    ]
